create procedure p_insert_transaction

@DEBIT_ACCOUNT_NO BIGINT
,@CREDIT_ACCOUNT_NO BIGINT
,@AMOUNT INT
AS
BEGIN
	DECLARE @DATE_TIME DATETIME;
	SET @DATE_TIME=GETDATE();
	INSERT INTO DEBIT_TRANSACTION_DETAILS(debit_account_no,debit_amount,debit_date_time) 
	VALUES(@DEBIT_ACCOUNT_NO,@AMOUNT,@DATE_TIME)

	DECLARE @ID INT;
	SET @ID= (SELECT id FROM DEBIT_TRANSACTION_DETAILS);

	INSERT INTO CREDIT_TRANSACTION_DETAILS(id_debit,credit_account_no,credit_amount,credit_date_time) 
	VALUES(@ID,@CREDIT_ACCOUNT_NO,@AMOUNT,@DATE_TIME)
	
	

END

EXEC p_insert_transaction 110010001111,110010001112,500

select * from	DEBIT_TRANSACTION_DETAILS
select * from	CREDIT_TRANSACTION_DETAILS
